### ISSUE TITLE
Laravel 5.4 - Phpstorm troubles

### ISSUE THREAD

**Issue by MarlonEtiene** [barryvdh/laravel-ide-helper#499]
Hello,
I dunno if I maked any mistake but when I try to use ide-helper with laravel 5.4 and phpstorm, many classes definition, autocompletion and other things not working.
Models not show his methods and some facades say "Multiple definitions".

I have a project in laravel 5.1 with same configuration, and all things of ide-helper provide works as well.

The huge difference, in laravel 5.4 I have installed ide-helper in "dev" only, and registered the ServiceProvider only for non production environment.

Any help or tip to me?

Thanks in advance.

PS. I'm attaching some screenshots of phpstorm
![model_method_not_found](https://cloud.githubusercontent.com/assets/1870776/25555339/137ba114-2cba-11e7-8927-40409807690a.png)
![model_method_not_found_2](https://cloud.githubusercontent.com/assets/1870776/25555332/d863b6ca-2cb9-11e7-8268-cf5df835027e.png)
![multiple_definitions](https://cloud.githubusercontent.com/assets/1870776/25555331/d862a366-2cb9-11e7-9eb1-68809caca3c0.png)

**Comment by exSnake** [comment]
Did you got a solution?

**Comment by MarlonEtiene** [comment]
Unfortunately nope.

**Comment by exSnake** [comment]
it's so frustrating!!!

**Comment by Jack-Bazarian** [comment]
Same problem!, laravel 5.2 was working fine, 5.4 most facades not working, although i can see the static methods in _ide_helper file.

**Comment by laoshaw** [comment]
just bought phpstorm for laravel and this plugin is not working, _very_ disappointed indeed.  Hopefully laravel-ide-helper can work with laravel 5.4 some day.

**Comment by laoshaw** [comment]
actually I could not even install it, it appears to be installed but composer under phpstorm reported it failed, which puzzled me. tried it under CLI and it seems got installed vendor/ but I'm unsure, how can i verify that it is installed without any errors?

**Comment by Artistan** [comment]
As pointed out @Jack-Bazarian - facades not working..
For me, this means that the ide helper parameter definitions are showing /NAMESPACE/Services/TYPE instead of the actual Type for the parameters.

## Using the facade...
![image](https://user-images.githubusercontent.com/801349/28148559-1d066c82-674d-11e7-83bf-4053bdb5bfb4.png)

## In the IDE helper file..
![image](https://user-images.githubusercontent.com/801349/28148595-5e8075c2-674d-11e7-9138-306e20d7afd4.png)

## And the actual method
![image](https://user-images.githubusercontent.com/801349/28148628-997599aa-674d-11e7-8d69-a332e306aab9.png)

**These should be AppNative/sie and Carbon/Carbon**
If that was correct, then it would work fine..

_I changed some variables, but you get the Gist._


ALSO

## I am getting the issue with not getting "where" definitions...
![image](https://user-images.githubusercontent.com/801349/28148754-5432b96c-674e-11e7-9517-2684ae794f3b.png)

_It looks like this has to do with Relations_
    `@return \Illuminate\Database\Eloquent\Relations\HasMany`

the relation calls where via __call rather than extending the \Illuminate\Database\Eloquent\Builder

```
    /**
     * Handle dynamic method calls to the relationship.
     *
     * @param  string  $method
     * @param  array   $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }

/////////////////////   here is the issue /////////////////
        $result = call_user_func_array([$this->query, $method], $parameters);

        if ($result === $this->query) {
            return $this;
        }

        return $result;
    }
```

The question now, is how to deal with this, does you add a helper / method to find the Relation models and add the mixin there or do you add the mixin to the laravel/framework?

## THIS FIXES THE ISSUE
```
/**
 * Class Relation
 * 
 * @package Illuminate\Database\Eloquent\Relations
 * @mixin \Eloquent
 */
```
add this above `abstract class Relation`  in your local Illuminate/Database/Eloquent/Relations/Relation.php

**Comment by Artistan** [comment]
this is more consistent with existing laravel mixins

```
/**
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
```

**Comment by gerchomat** [comment]
I had the same problem with laravel version 5.4.30. 
I downgrade my project to **5.4.28 and it works!**

**Comment by jatinparmar96** [comment]
I solved this issue by downloading the ide-helper manually and through cmd and then updating the providers class as shown in the readme.md.

**Comment by bakcay** [comment]
> composer require barryvdh/laravel-ide-helper:v2.3.2 -n --no-progress

This has saved my day. thanks laoshaw

**Comment by mfn** [comment]
@barryvdh another issue which was fixed with `@mixin` support, can be closed :}
