### ISSUE TITLE
_ide_helper.php break the autocomplete in PHPStorm

### ISSUE THREAD

**Issue by Coldzer0** [barryvdh/laravel-ide-helper#449]
when i update to Laravel **v5.4.12**
i use IDE Helper **v2.2** ( i update it to the **Dev** Version **v2.3.0** still the same )

only when i **delete** the "**_ide_helper.php**" the autocomplete works fine.

only **.phpstorm.meta.php** & **_ide_helper_models.php** works fine

**Comment by bognerf** [comment]
Same here.

barryvdh/laravel-ide-helper           v2.3.0
laravel/framework                     v5.4.11

PhpStorm 2016.3.1
Build #PS-163.9735.1

**Comment by Kurre** [comment]
Hmm, I haven't seen such problems lately. Need to check..

Can you give an example of situation when autocomplete doesn't work?

**Comment by bognerf** [comment]
For example, create a new model: php artisan make:model Test

````php 
<?php
// File: Test.php
namespace App\Db;

use Illuminate\Database\Eloquent\Model;

class Test extends Model
{
    //
}
````

Within this class, PHPStorm nags about "multiple definitions" of Model, one of which is to be found in _ide_helper.php. PHPStorm won't show any autocompletion, nothing about properties overwritten or inherited, and so forth...

Deleting the Model part from _ide_helper.php solves the problem for me so far.

I didn't experience this behaviour in **laravel-ide-helper**  in combination with Laravel 5.1 or 5.2 using an identical setup like the project in question here. PHPStorm does complain about "multiple definitions" in the latter cases as well, but still autocompletion and all the other inspections continue to work.

If I can provide more information regarding this, I would be glad to help.

**Comment by jschram** [comment]
I'm seeing the same issue with 2.3.0; Eloquent mixin doesn't seem to work, so methods like `belongsTo`, `save`, etc. are not recognized by PhpStorm. Downgrading to 2.2.3 resolved this issue.

Running latest stable release of PhpStorm (2016.3.2, Build #PS-163.10504.2) and php 5.6.29 (installed through brew) on Mac OSX 10.10.5 and my laravel framework is at version 5.4.12.

**Comment by barryvdh** [comment]
Can you try with https://github.com/barryvdh/laravel-ide-helper/commit/25c8de637ddf79567d721c1856616be01db7b960

**Comment by barryvdh** [comment]
You can install it with v2.3.1 in a couple of minutes; https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.3.1

**Comment by jschram** [comment]
Using 2.3.1 fixes the issue with belongsTo and such, but now static methods aren't found in the models.

**Comment by barryvdh** [comment]
Are you extendin Eloquent or Model?

**Comment by jschram** [comment]
I'm extending `Eloquent` and have `@mixin Eloquent` in my phpDoc

**Comment by barryvdh** [comment]
And with `@mixin \Illuminate\Database\Eloquent\Builder`  instead of Eloquent?

**Comment by jschram** [comment]
Yes, that is working! Should that be the default output from the ide-helper:models ?

**Comment by jschram** [comment]
Update: External access to static methods (like `find`) on models is still not recognized as valid by PhpStorm.

**Comment by barryvdh** [comment]
Can you try with https://github.com/barryvdh/laravel-ide-helper/releases/tag/v2.3.2 ? Should be able to complete when extending `Eloquent` or using `@mixin \Eloquent`

**Comment by bognerf** [comment]
With v2.3.2 PHPStorm still "complains" about multiple definitions (which is to be expected), but overwritten properties and auto completion works for me again like I was used to.

**Comment by jschram** [comment]
Autocomplete on models work correctly with 2.3.2, including static calls.

Not sure if related, but I did see a new issue where the `Route::middleware` and `Route::prefix` weren't found on the facade:
![image](https://cloud.githubusercontent.com/assets/10851379/23251291/1109a5ce-f9ad-11e6-892b-51714b4186e7.png)

**Comment by eness** [comment]
having the same issue. I always get "multiple definitions ..." error(s) for eloquent models from phpstorm's inspector

**Comment by justnorris** [comment]
Has anyone figured out how to solve the "multiple definitions" error? It prevents autocomplete in phpStorm :(

**Comment by barryvdh** [comment]
It shouldn't prevent autocomplete, but add them both :(

**Comment by justnorris** [comment]
Yeah, turns out it doesn't prevent autocomplete after all. But for some reason phpStorm isn't able to follow relationships. I can't get any autocomplete on `Foobar::firstOrCreate()`

What's even more interesting is that phpStorm for some reason marks `$foobar->barbar()->create()` as `barbar()` not found, even though `barbar()` is `public funciton barbar()` in`Foobar` and defines a `belongsTo` relationship.

**Comment by madsem** [comment]
Is there any way around the multiple definitions warnings? I have the exact same problem, using a seperate models file with ide helper. For me $domain->tags() doesn't work with autocompletion or clicking on it, because of the multiple class name definitions.

I would rather not have ide helper overwrite my models, any other way? 🥇

**Comment by pastuh** [comment]
How to fix in phpstorm: Method 'prefix' not found in Route

**Comment by mvilera** [comment]
I'm having problems with Route facade too, method prefix is not defined using lastest version on Laravel 5.4

**Comment by PanCrucian** [comment]
Route::middleware and Route::prefix not working too Laravel 5.5

**Comment by bigstepdenmark** [comment]
Route::middleware still not work :s

**Comment by danielabbatt** [comment]
Route::prefix still appears to not be recognised

**Comment by dorin-niscu** [comment]
The same for $this->app->routesAreCached() inside a service provider.
![prtscr capture_2](https://user-images.githubusercontent.com/4982856/42748274-3b91325a-88e8-11e8-8e02-264698f81d35.jpg)

**Comment by mfn** [comment]
Ugh, this issue turned into a bit of dumpster for a lot of different things :>

The initial issue was fixed with 2.3.2, as for the other small things: is suggest to re-check with the latest version if it's still broken and then search issues and comment/vote on existing one or create new issue for dedicated problems.

@barryvdh I vote for closing this one :}
