### PR TITLE
Fix alias fake error

### PR DESCRIPTION
**Pull request by WentTheFox**
## Summary

The helper generation breaks when the `Laravel\Socialite\Socialite` facade's `fake` method (introduced in https://github.com/laravel/socialite/pull/756) is being called by the IDE helper, because the method has a required argument. In PHP 8.5 this causes an `ArgumentCountError` as seen below:

```
> Illuminate\Foundation\ComposerScripts::postUpdate
> @php artisan ide-helper:generate

   ArgumentCountError 

  Too few arguments to function Laravel\Socialite\Socialite::fake(), 0 passed in vendor/barryvdh/laravel-ide-helper/src/Alias.php on line 254 and at least 1 expected

  at vendor/laravel/socialite/src/Socialite.php:39
     35▕      * @param  string  $driver
     36▕      * @param  \Laravel\Socialite\Contracts\User|\Closure|array|null  $user
     37▕      * @return \Laravel\Socialite\Testing\SocialiteFake
     38▕      */
  ➜  39▕     public static function fake(string $driver, $user = null)
     40▕     {
     41▕         $root = static::getFacadeRoot();
     42▕ 
     43▕         if ($root instanceof SocialiteFake) {

      +18 vendor frames 

  19  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

Script @php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1
```

ArgumentCountError screenshot

The goal of this change is to fully ignore the error so the `ide-helper:generate` command can complete without crashing, as it seems the missing `catch` block causes the error to be thrown despite being wrapped in `try`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [ ] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by Orrison** [comment]
Seeing this issue as well

**Comment by FallenKnight85** [comment]
Experiencing this issue as well

**Comment by WentTheFox** [comment]
@barryvdh I think the tests failed due to the
```
return ’’;
```
in the `MockFacade` class, that might have to be replaced with an actual class string. I did not see that earlier since the pipelines were waiting for approval.

**Comment by barryvdh** [comment]
Yes fixed that already; https://github.com/barryvdh/laravel-ide-helper/commit/c95825a7452769cabdb10f18691d6eb1063d31e4

**Comment by barryvdh** [comment]
This is tagged, so should be good now.
